services:
  # ── Application Laravel ──
  proimmo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proimmo-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - proimmo-network
    working_dir: /var/www
    environment:
      # Evite les problèmes de session
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8083
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

  # ── Serveur web Nginx ──
  proimmo-web:
    image: nginx:alpine
    container_name: proimmo-web
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d   # Contient default.conf avec config Laravel
    depends_on:
      - proimmo-app
    networks:
      - proimmo-network

  # ── Base de données MySQL ──
  proimmo-db:
    image: mysql:8.0
    container_name: proimmo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: proimmo
      MYSQL_ROOT_PASSWORD: yes
    volumes:
      - proimmo_dbdata:/var/lib/mysql
    networks:
      - proimmo-network

# ── Réseau Docker ──
networks:
  proimmo-network:
    driver: bridge

# ── Volume pour persistance MySQL ──
volumes:
  proimmo_dbdata: